name: "DHCP tracker"
description: >-
  Watch for specific mac addresses, notify home assistant when they are assigned
  an IP address and optionally when the IP address no longer responds to ICMP ping
version: "0.2.3"
slug: "dhcp_tracker"
init: false
host_network: true
homeassistant_api: true
arch:
  - aarch64
  # - amd64
  # - armhf
  # - armv7
  # - i386
schema:
  mac_addresses:
    - str
  enable_device_tracker: bool
  create_device_trackers: bool
options:
  mac_addresses:
    - null
  enable_device_tracker: false
  create_device_trackers: false
